### PR TITLE
Added configuration in so decoding and displaying Eric's TT GLM grids…

### PR DESCRIPTION
**Pull request by tiffanycmeyer13**
… work as well as the new ISatSS GLM grids

### CODE REVIEW

**Review by srcarter3 — COMMENTED** [review]
I see the addition of "TT" for Texas Tech (Eric's feed), but I'm still a little confused, are there also entries for "our" (the aws one through nws) feed?  So that both products will be decoded.  Maybe the comparison is just leaving them out?

**Comment by tiffanycmeyer13** [comment]
Yes, for the EDEX side, there is a whole new file for the NWS GLM grids (https://github.com/Unidata/awips2-goesr/blob/unidata_18.2.1/edexOsgi/com.raytheon.uf.edex.plugin.goesr/utility/common_static/base/satellite/goesr/descriptions/Level2/GLMG_FD_tile.xml)

For the CAVE/styleRules side, there are entries below for the NWS GLM grids if you look at the full file (those didn't change so they don't show up in the diff).

**Comment by srcarter3** [comment]
Oh I see, so you had previously added new edex files for our new feed, but had never removed or changed the name of the "old" files?
So there were two different files for the different feed types, but they both had the same names for the products?

**Comment by tiffanycmeyer13** [comment]
Correct

**Pull request merged**
